server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: absence-service
          uri: lb://ABSENCE-SERVICE
          predicates:
            - Path=/absences/**

        - id: emploi-service
          uri: lb://EMPLOI-SERVICE
          predicates:
            - Path=/emploi/**

        - id: auth-service
          uri: lb://USER-AUTH-SERVICE
          predicates:
            - Path=/api/users/**

        - id: auth-users
          uri: lb://USER-AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        - id: admin-service
          uri: lb://USER-AUTH-SERVICE
          predicates:
            - Path=/admin/**

        - id: responsible-service
          uri: lb://CLASS-RESPONSIBILITY-SERVICE
          predicates:
            - Path=/api/responsible/**

        - id: document-sharing
          uri: lb://DOCUMENT-SHARING
          predicates:
            - Path=/api/document/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
